---
- name: Install packages and configure WordPress
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - mysql-server
          - wget
          - unzip
        state: present          # ✅ Fixed spelling: was "persent"
        update_cache: yes       # ✅ Fixed spelling: was "update_cash"

    - name: Download WordPress
      get_url:                  # ✅ Fixed: use `get_url` instead of `wget`
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz   # ✅ Fixed typo: was .tar.giz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set ownership of WordPress files
      file:
        path: /var/www/html/wordpress    # ✅ Target the extracted folder
        recurse: yes
        owner: www-data
        group: www-data
