- name: Install packages and configure WordPress
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - mysql-server
          - wget
          - unzip
        state: present
        update_cache: yes

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Move WordPress files to web root (safe shell)
      shell: |
        shopt -s nullglob
        mv /var/www/html/wordpress/* /var/www/html/
      args:
        executable: /bin/bash

    - name: Clean up extra files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html/index.html
        - /var/www/html/wordpress
        - /tmp/wordpress.tar.gz

    - name: Set ownership of WordPress files
      file:
        path: /var/www/html
        recurse: yes
        owner: www-data
        group: www-data
